title: GitHub Pages course  
author: Eduardo Brito 
email: eebritosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website ws mad ein order to do the GitHub Pages free course

# social links
github_username:  eduardobritosan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
